# Generated by Django 3.2.8 on 2022-03-03 13:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Company that contracted GoVanguard for a phishing campaign.', max_length=32, null=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liname', models.CharField(help_text='The registered company name with LinkedIn.', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Company Profiles',
            },
        ),
        migrations.CreateModel(
            name='Exclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1019)),
            ],
        ),
        migrations.CreateModel(
            name='ExclusionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Exclusion Lists',
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1019)),
            ],
        ),
        migrations.CreateModel(
            name='NameList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Name Lists',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Owner of the social engineering campaign the company is contracting with GoVanguard.', max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhishingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, help_text='Service providing the mail exchange server.', max_length=4, null=True)),
                ('enumeration', models.CharField(blank=True, help_text='Service providing the email enumeration service.', max_length=4, null=True)),
                ('domain', models.URLField(blank=True, help_text='The location to launch a phishing campaign from.', max_length=2048, null=True)),
                ('efrom', models.EmailField(blank=True, help_text='The e-mail address you are sending an e-mail from.', max_length=320, null=True)),
                ('to', models.EmailField(blank=True, help_text='The e-mail address you want to preview the e-mail in.', max_length=320, null=True)),
                ('subject', models.CharField(blank=True, help_text='The subject for the phishing campaign e-mail.', max_length=998, null=True)),
                ('keyword', models.CharField(blank=True, help_text='The template keyword used to substitute in the phishing domain.', max_length=20, null=True)),
                ('attachment', models.FileField(null=True, upload_to='uploads/%d %B %Y/')),
                ('body', models.CharField(blank=True, help_text='The body of the phishing campaign e-mail.', max_length=10000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Phishing Emails',
            },
        ),
        migrations.CreateModel(
            name='PhishingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Phishing Lists',
            },
        ),
        migrations.CreateModel(
            name='PhishingTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(help_text='Company contracting the social engineering campaign from GoVanguard.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='pondering.company')),
                ('owner', models.ForeignKey(help_text='Owner of the social engineering campaign the company is contracting with GoVanguard.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='pondering.owner')),
            ],
            options={
                'verbose_name_plural': 'Phishing Trips',
            },
        ),
        migrations.CreateModel(
            name='PhishingWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The phishing website.', max_length=2048)),
                ('hyperlink', models.CharField(blank=True, help_text='The hyperlink you want the phishing website to appear as.', max_length=2048, null=True)),
            ],
            options={
                'verbose_name_plural': 'Phishing Websites',
            },
        ),
        migrations.CreateModel(
            name='PointOfContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Point of contact that knows the most about a specific company.', max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TargetEmailAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('38dc6363-8bc3-4e73-8d0f-043d0c2799a3'), help_text='Unique ID for this particular e-mail address.', primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, help_text='The e-mail address you are sending an e-mali to.', max_length=320, null=True)),
            ],
            options={
                'verbose_name_plural': 'Target Email Addresses',
            },
        ),
        migrations.CreateModel(
            name='TargetWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The client website that actively hosts a Simple Mail Transfer Protocol (SMTP) service.', max_length=2048)),
            ],
            options={
                'verbose_name_plural': 'Target Websites',
            },
        ),
        migrations.CreateModel(
            name='PhishingTripInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular phishing trip.', primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(max_length=20)),
                ('schedulingStatus', models.CharField(blank=True, choices=[('p', 'Pending'), ('s', 'Signed'), ('a', 'Approved')], default='p', help_text='Phishing campaign contract status.', max_length=1)),
                ('operationalStatus', models.CharField(blank=True, choices=[('a', 'Awaiting Approval'), ('i', 'Initializing'), ('r', 'Ready'), ('p', 'Phishing'), ('c', 'Complete'), ('e', 'Error')], default='a', help_text='Phishing campaign operational status.', max_length=1)),
                ('email', models.ForeignKey(help_text='The phishing e-mail to be used during this campaign.', null=True, on_delete=django.db.models.deletion.CASCADE, to='pondering.phishingemail')),
                ('nameList', models.OneToOneField(help_text='The list of names used to generate the phishing list.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='pondering.namelist')),
                ('pList', models.ForeignKey(help_text='List of potential e-mail addresses.', null=True, on_delete=django.db.models.deletion.CASCADE, to='pondering.phishinglist')),
                ('pond', models.OneToOneField(help_text='The phishing website.', null=True, on_delete=django.db.models.deletion.CASCADE, to='pondering.phishingwebsite')),
                ('target', models.OneToOneField(help_text='The client website that actively hosts a Simple Mail Transfer Protocol (SMTP) service.', null=True, on_delete=django.db.models.deletion.CASCADE, to='pondering.targetwebsite')),
                ('trip', models.ForeignKey(help_text='Create a phishing trip, which may include multiple domains.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='pondering.phishingtrip')),
            ],
            options={
                'verbose_name_plural': 'Phishing Trip Instances',
            },
        ),
        migrations.AddField(
            model_name='phishinglist',
            name='phishingList',
            field=models.ForeignKey(help_text='List of potential e-mail addresses.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='pondering.targetemailaddress'),
        ),
        migrations.AddField(
            model_name='company',
            name='poc',
            field=models.ForeignKey(help_text='Point of contact within GoVanguard that knows the most about a specific company.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='pondering.pointofcontact'),
        ),
    ]
