# Generated by Django 3.2.8 on 2021-12-27 18:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishingemail',
            name='enumeration',
            field=models.CharField(blank=True, help_text='Service providing the email enumeration service.', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='phishingtripinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6757d1cc-0e09-4cc2-bd87-f45f43473612'), help_text='Unique ID for this particular phishing trip.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='targetemailaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c8bab60e-f624-481f-a6e3-0d191d86b166'), help_text='Unique ID for this particular e-mail address.', primary_key=True, serialize=False),
        ),
    ]
