# Generated by Django 3.2.8 on 2021-11-22 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pointofcontact',
            old_name='poc',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='phishingtrip',
            name='poc',
        ),
        migrations.AddField(
            model_name='phishingtrip',
            name='owner',
            field=models.ForeignKey(help_text='Owner of the social engineering campaign the company is contracting with GoVanguard.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='pondering.owner'),
        ),
    ]
