# Generated by Django 3.2.8 on 2022-01-11 14:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='phishingtripinstance',
            name='nameList',
            field=models.OneToOneField(help_text='The list of names used to generate the phishing list.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='pondering.namelist'),
        ),
        migrations.AlterField(
            model_name='phishingtripinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0f0504e4-0e81-481d-848a-4a6508fab89e'), help_text='Unique ID for this particular phishing trip.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='targetemailaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d36b5d3f-7a90-43bf-816b-4cb534428f0d'), help_text='Unique ID for this particular e-mail address.', primary_key=True, serialize=False),
        ),
    ]
