# Generated by Django 3.2.8 on 2022-03-03 21:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetemailaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fc435904-74b1-4006-a3af-033666dd82f5'), help_text='Unique ID for this particular e-mail address.', primary_key=True, serialize=False),
        ),
    ]
