# Generated by Django 3.2.8 on 2021-12-27 18:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0002_auto_20211227_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phishingtripinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cfe6b087-68cd-4270-a6a1-fb1b1c52d825'), help_text='Unique ID for this particular phishing trip.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='targetemailaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4a2798d1-eb64-4723-8c52-dab090fd9a1b'), help_text='Unique ID for this particular e-mail address.', primary_key=True, serialize=False),
        ),
    ]
