# Generated by Django 3.2.8 on 2022-01-18 18:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0002_auto_20220111_0934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FullName',
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name_plural': 'Company Profiles'},
        ),
        migrations.AlterModelOptions(
            name='exclusionlist',
            options={'verbose_name_plural': 'Exclusion Lists'},
        ),
        migrations.AlterModelOptions(
            name='namelist',
            options={'verbose_name_plural': 'Name Lists'},
        ),
        migrations.AlterModelOptions(
            name='phishingemail',
            options={'verbose_name_plural': 'Phishing Emails'},
        ),
        migrations.AlterModelOptions(
            name='phishinglist',
            options={'verbose_name_plural': 'Phishing Lists'},
        ),
        migrations.AlterModelOptions(
            name='phishingtrip',
            options={'verbose_name_plural': 'Phishing Trips'},
        ),
        migrations.AlterModelOptions(
            name='phishingtripinstance',
            options={'verbose_name_plural': 'Phishing Trip Instances'},
        ),
        migrations.AlterModelOptions(
            name='phishingwebsite',
            options={'verbose_name_plural': 'Phishing Websites'},
        ),
        migrations.AlterModelOptions(
            name='targetemailaddress',
            options={'verbose_name_plural': 'Target Email Addresses'},
        ),
        migrations.AlterModelOptions(
            name='targetwebsite',
            options={'verbose_name_plural': 'Target Websites'},
        ),
        migrations.AddField(
            model_name='exclusionlist',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phishingtripinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular phishing trip.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='targetemailaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3c87115a-62a8-4879-bb46-60671ee4a149'), help_text='Unique ID for this particular e-mail address.', primary_key=True, serialize=False),
        ),
    ]
