# Generated by Django 3.2.8 on 2021-11-23 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0002_auto_20211122_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phishingtripinstance',
            name='operationalSatus',
        ),
        migrations.RemoveField(
            model_name='phishingtripinstance',
            name='owner',
        ),
        migrations.AddField(
            model_name='phishingtripinstance',
            name='operationalStatus',
            field=models.CharField(blank=True, choices=[('a', 'Awaiting Approval'), ('i', 'Initializing'), ('r', 'Ready'), ('p', 'Phishing'), ('c', 'Complete'), ('e', 'Error')], default='a', help_text='Phishing campaign operational status.', max_length=1),
        ),
        migrations.AlterField(
            model_name='phishingtripinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c76da6cb-34cf-45d8-b5c5-66a193f07110'), help_text='Unique ID for this particular phishing trip.', primary_key=True, serialize=False),
        ),
    ]
