# Generated by Django 3.2.8 on 2021-12-27 18:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0003_auto_20211227_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phishingtripinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2f436c33-e2dc-44cc-876a-5883d5887709'), help_text='Unique ID for this particular phishing trip.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='targetemailaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('64fe93b0-2b7a-4c44-9e0c-b63796c9875d'), help_text='Unique ID for this particular e-mail address.', primary_key=True, serialize=False),
        ),
    ]
