# Generated by Django 3.2.8 on 2022-01-18 18:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0003_auto_20220118_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetemailaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9f7b748b-6d74-4138-9ae2-a4ec23b29f33'), help_text='Unique ID for this particular e-mail address.', primary_key=True, serialize=False),
        ),
    ]
