# Generated by Django 3.2.8 on 2021-11-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0003_auto_20211103_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishingtripinstance',
            name='domain',
            field=models.ManyToManyField(help_text="Enter the URL containing the company's SMTP server.", to='pondering.Domain'),
        ),
    ]
