# Generated by Django 3.2.8 on 2021-11-23 18:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0003_auto_20211123_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phishingemail',
            name='targetWebsite',
        ),
        migrations.AlterField(
            model_name='phishingtripinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e6a95d44-043c-46c6-81c4-18aeb3819a10'), help_text='Unique ID for this particular phishing trip.', primary_key=True, serialize=False),
        ),
    ]
