# Generated by Django 3.2.8 on 2021-11-23 22:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0004_auto_20211123_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phishingemail',
            name='mailTo',
        ),
        migrations.AddField(
            model_name='phishingtripinstance',
            name='email',
            field=models.OneToOneField(help_text='The phishing e-mail to be used during this campaign.', null=True, on_delete=django.db.models.deletion.CASCADE, to='pondering.phishingemail'),
        ),
        migrations.AddField(
            model_name='phishingtripinstance',
            name='pList',
            field=models.ForeignKey(help_text='List of potential e-mail addresses.', null=True, on_delete=django.db.models.deletion.CASCADE, to='pondering.phishinglist'),
        ),
        migrations.AlterField(
            model_name='phishinglist',
            name='phishingList',
            field=models.ForeignKey(help_text='List of potential e-mail addresses.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='pondering.targetemail'),
        ),
        migrations.AlterField(
            model_name='phishingtripinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('864872c0-5e75-4282-8d88-d9fdce0c78b3'), help_text='Unique ID for this particular phishing trip.', primary_key=True, serialize=False),
        ),
    ]
