# Generated by Django 3.2.8 on 2021-11-04 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0004_phishingtripinstance_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phishingtripinstance',
            name='domain',
        ),
        migrations.AddField(
            model_name='phishingtripinstance',
            name='domain',
            field=models.ForeignKey(help_text='Register the URL(s) that actively host a Simple Mail Transfer Protocol (SMTP) service.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='pondering.domain'),
        ),
        migrations.AlterField(
            model_name='phishingtripinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Pending'), ('r', 'Accepted'), ('a', 'Approved')], default='p', help_text='Phishing campaign status.', max_length=1),
        ),
        migrations.AlterField(
            model_name='phishingtripinstance',
            name='trip',
            field=models.ForeignKey(help_text='Create a phishing trip, which may include multiple domains.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='pondering.phishingtrip'),
        ),
    ]
