# Generated by Django 3.2.8 on 2021-11-24 15:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0005_auto_20211123_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phishingtripinstance',
            name='email',
            field=models.ForeignKey(help_text='The phishing e-mail to be used during this campaign.', null=True, on_delete=django.db.models.deletion.CASCADE, to='pondering.phishingemail'),
        ),
        migrations.AlterField(
            model_name='phishingtripinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e7e2d435-059d-4069-abf5-b1f1b9901716'), help_text='Unique ID for this particular phishing trip.', primary_key=True, serialize=False),
        ),
    ]
