# Generated by Django 3.2.8 on 2021-11-04 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0005_auto_20211104_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phishingtrip',
            old_name='authority',
            new_name='poc',
        ),
    ]
