# Generated by Django 3.2.8 on 2021-12-29 21:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0005_auto_20211229_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phishingtripinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c81cfe1a-aab8-4331-96e7-ccd0d1446443'), help_text='Unique ID for this particular phishing trip.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='targetemailaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f889cd6f-423e-42e7-88fd-4de05efe893c'), help_text='Unique ID for this particular e-mail address.', primary_key=True, serialize=False),
        ),
    ]
