# Generated by Django 3.2.8 on 2021-11-16 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0006_rename_authority_phishingtrip_poc'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='The phishing website.', max_length=2048)),
                ('hyperlink', models.CharField(blank=True, help_text='The hyperlink you want the phishing website to appear as.', max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhishingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailFrom', models.EmailField(blank=True, help_text='The e-mail address you are sending an e-mail from.', max_length=320, null=True)),
                ('mailTo', models.EmailField(blank=True, help_text='The e-mail address you are sending an e-mail to.', max_length=320, null=True)),
                ('preview', models.EmailField(blank=True, help_text='The e-mail address you want to preview the e-mail in.', max_length=320, null=True)),
                ('subject', models.CharField(blank=True, help_text='The subject for the phishing campaign e-mail.', max_length=998, null=True)),
                ('body', models.CharField(blank=True, help_text='The body of the phishing campaign e-mail.', max_length=10000, null=True)),
                ('keyword', models.CharField(blank=True, help_text='The template keyword used to substitute in the phishing domain.', max_length=20, null=True)),
                ('phishingDomain', models.ForeignKey(help_text='Hyperlink representation of the phishing domain.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='pondering.phishingdomain')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The client website.', max_length=2048)),
            ],
        ),
        migrations.RemoveField(
            model_name='phishingtripinstance',
            name='domain',
        ),
        migrations.AlterField(
            model_name='phishingtripinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Pending'), ('s', 'Signed'), ('a', 'Approved')], default='p', help_text='Phishing campaign status.', max_length=1),
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.AddField(
            model_name='phishingemail',
            name='target',
            field=models.ForeignKey(help_text='Register the URL that actively hosts a Simple Mail Transfer Protocol (SMTP) service.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='pondering.target'),
        ),
        migrations.AddField(
            model_name='phishingtripinstance',
            name='target',
            field=models.ForeignKey(help_text='Register the URL(s) that actively hosts a Simple Mail Transfer Protocol (SMTP) service.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='pondering.target'),
        ),
    ]
