# Generated by Django 3.2.8 on 2022-01-03 13:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0006_auto_20211229_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='linkedin',
            field=models.CharField(blank=True, help_text='Registered company name with LinkedIn.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='phishingtripinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('daa08324-0091-4f6d-84a0-daab6f8b4c13'), help_text='Unique ID for this particular phishing trip.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='targetemailaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6fbea728-bf53-4c72-8226-883c84052d05'), help_text='Unique ID for this particular e-mail address.', primary_key=True, serialize=False),
        ),
    ]
