# Generated by Django 3.2.8 on 2021-11-29 18:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0006_auto_20211124_1000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TargetEmail',
            new_name='TargetEmailAddress',
        ),
        migrations.CreateModel(
            name='GoPhish',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pondering.phishingtripinstance',),
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterField(
            model_name='phishingtripinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f8e5c064-652b-4ab2-8fd9-8861f22b4cf3'), help_text='Unique ID for this particular phishing trip.', primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='PhishingResult',
        ),
    ]
