# Generated by Django 3.2.8 on 2022-01-03 13:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0007_auto_20220103_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liname', models.CharField(help_text='The registered company name with LinkedIn.', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='linkedin',
        ),
        migrations.AlterField(
            model_name='phishingtripinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('44114b40-404d-4627-98ce-d08db3375fea'), help_text='Unique ID for this particular phishing trip.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='targetemailaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4492d18f-78bf-47a4-a763-e480a9a826c2'), help_text='Unique ID for this particular e-mail address.', primary_key=True, serialize=False),
        ),
    ]
