# Generated by Django 3.2.8 on 2021-11-30 13:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0007_auto_20211129_1305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoPhish',
        ),
        migrations.CreateModel(
            name='GoPhishing',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pondering.phishingtripinstance',),
        ),
        migrations.AlterField(
            model_name='phishingtripinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3aa44e07-85a7-49de-8d70-a92ada19a9d9'), help_text='Unique ID for this particular phishing trip.', primary_key=True, serialize=False),
        ),
    ]
