# Generated by Django 3.2.8 on 2021-11-30 13:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0008_auto_20211130_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phishingemail',
            old_name='mailFrom',
            new_name='emailFrom',
        ),
        migrations.AlterField(
            model_name='phishingtripinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('011212ab-cb24-469d-9fdf-d3b8f6cef4d0'), help_text='Unique ID for this particular phishing trip.', primary_key=True, serialize=False),
        ),
    ]
