# Generated by Django 3.2.8 on 2022-01-03 14:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0008_auto_20220103_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phishingtripinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d654fb79-4b8a-46b6-a531-ef41c09c80e5'), help_text='Unique ID for this particular phishing trip.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='targetemailaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dbec4013-8394-43be-8c4e-aa1b4503f60b'), help_text='Unique ID for this particular e-mail address.', primary_key=True, serialize=False),
        ),
    ]
