# Generated by Django 3.2.8 on 2021-12-01 16:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0009_auto_20211130_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phishingtripinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d69ab109-9257-40fa-aef2-aaa8578d6271'), help_text='Unique ID for this particular phishing trip.', primary_key=True, serialize=False),
        ),
    ]
