# Generated by Django 3.2.8 on 2021-12-02 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0010_alter_phishingtripinstance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishingemail',
            name='domain',
            field=models.URLField(blank=True, help_text='The location to launch a phishing campaign from.', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='phishingtripinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('67004e96-b1aa-4143-9ffb-3a2c97771992'), help_text='Unique ID for this particular phishing trip.', primary_key=True, serialize=False),
        ),
    ]
