# Generated by Django 3.2.8 on 2021-12-03 17:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0011_auto_20211202_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phishingemail',
            old_name='body',
            new_name='Body',
        ),
        migrations.RenameField(
            model_name='phishingemail',
            old_name='domain',
            new_name='Domain',
        ),
        migrations.RenameField(
            model_name='phishingemail',
            old_name='emailFrom',
            new_name='From',
        ),
        migrations.RenameField(
            model_name='phishingemail',
            old_name='keyword',
            new_name='Keyword',
        ),
        migrations.RenameField(
            model_name='phishingemail',
            old_name='preview',
            new_name='Preview',
        ),
        migrations.RenameField(
            model_name='phishingemail',
            old_name='subject',
            new_name='Subject',
        ),
        migrations.AlterField(
            model_name='phishingtripinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6e5d15de-af2a-45ec-9b87-2b4051cff16f'), help_text='Unique ID for this particular phishing trip.', primary_key=True, serialize=False),
        ),
    ]
