# Generated by Django 3.2.8 on 2021-12-03 17:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0012_auto_20211203_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phishingemail',
            old_name='Preview',
            new_name='To',
        ),
        migrations.AlterField(
            model_name='phishingtripinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fa360f57-2b4b-408e-8d1a-0600f9dd3741'), help_text='Unique ID for this particular phishing trip.', primary_key=True, serialize=False),
        ),
    ]
