# Generated by Django 3.2.8 on 2021-12-03 19:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0013_auto_20211203_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phishingemail',
            old_name='Body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='phishingemail',
            old_name='Domain',
            new_name='domain',
        ),
        migrations.RenameField(
            model_name='phishingemail',
            old_name='From',
            new_name='efrom',
        ),
        migrations.RenameField(
            model_name='phishingemail',
            old_name='Keyword',
            new_name='keyword',
        ),
        migrations.RenameField(
            model_name='phishingemail',
            old_name='Subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='phishingemail',
            old_name='To',
            new_name='to',
        ),
        migrations.AlterField(
            model_name='phishingtripinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ea5a2e3b-fc48-432b-aacc-391aef97acf9'), help_text='Unique ID for this particular phishing trip.', primary_key=True, serialize=False),
        ),
    ]
