# Generated by Django 3.2.8 on 2021-12-03 19:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0014_auto_20211203_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phishingemail',
            old_name='body',
            new_name='Body',
        ),
        migrations.RenameField(
            model_name='phishingemail',
            old_name='domain',
            new_name='Domain',
        ),
        migrations.RenameField(
            model_name='phishingemail',
            old_name='efrom',
            new_name='From',
        ),
        migrations.RenameField(
            model_name='phishingemail',
            old_name='keyword',
            new_name='Keyword',
        ),
        migrations.RenameField(
            model_name='phishingemail',
            old_name='subject',
            new_name='Subject',
        ),
        migrations.RenameField(
            model_name='phishingemail',
            old_name='to',
            new_name='To',
        ),
        migrations.AddField(
            model_name='phishingemail',
            name='Service',
            field=models.CharField(blank=True, help_text='Service providing a mail exchange server.', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='phishingtripinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4a0559ab-c266-4d10-95a1-e735899137f4'), help_text='Unique ID for this particular phishing trip.', primary_key=True, serialize=False),
        ),
    ]
