# Generated by Django 3.2.8 on 2021-12-03 20:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0016_alter_phishingtripinstance_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phishingemail',
            old_name='Body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='phishingemail',
            old_name='Domain',
            new_name='domain',
        ),
        migrations.RenameField(
            model_name='phishingemail',
            old_name='From',
            new_name='efrom',
        ),
        migrations.RenameField(
            model_name='phishingemail',
            old_name='Keyword',
            new_name='keyword',
        ),
        migrations.RenameField(
            model_name='phishingemail',
            old_name='Subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='phishingemail',
            old_name='To',
            new_name='to',
        ),
        migrations.RemoveField(
            model_name='phishingemail',
            name='Service',
        ),
        migrations.AddField(
            model_name='phishingemail',
            name='service',
            field=models.CharField(blank=True, help_text='Service providing the mail exchange server.', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='phishingtripinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d0cfe01a-f002-4a41-aa31-1c7d454b8f33'), help_text='Unique ID for this particular phishing trip.', primary_key=True, serialize=False),
        ),
    ]
