# Generated by Django 3.2.8 on 2021-12-21 19:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pondering', '0017_auto_20211203_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phishingtripinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8f2fba3b-1317-4031-8073-a0d9b63548fd'), help_text='Unique ID for this particular phishing trip.', primary_key=True, serialize=False),
        ),
    ]
